### ISSUE TITLE
[WIP] Major 14 manifest

### ISSUE THREAD

**Issue by makhnatkin** [gravity-ui/markdown-editor#423]
## Description
A set of changes in a future major release

### Deps
- [x] Dependencies updated
  - [x] diplodoc-platform/transform@4.32.2
  - [x] prosemirror
  - [x] codemirror
  - [x] others

### Extensions 
- [x] Extensions that do not connect by default have been moved to a new folder (most likely additional)
    - [x] YfmHtmlBlock, wil be renamed
    - [x] Mermaid
    - [ ] Latex
    - [x] GPT
- [ ] Re-exports have been removed (which were for backward compatibility)
   - [x] GPT
   - [ ] YfmHtml

### Configs
- [x] Settings are grouped into editor options types

### TODO, FIXME
- [x] The issues related to the transition to a new major have been resolved 

Is there something else?
